version: "3"

services:
  proxy:
    image: quay.io/sentinelc/proxy:${PROXY_TAG}
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./volumes/ssl:/ssl
    env_file:
      - ./configs/proxy.env
    networks:
      - proxy

  vouch:
    image: quay.io/vouch/vouch-proxy:0.37.3
    restart: always
    ports:
      - "9090:9090"
    env_file:
      - ./configs/vouch.env
    networks:
      - proxy

  api_db:
    image: postgres:14.1
    restart: always
    env_file:
      - ./configs/api_db.env
    networks:
      - django
    volumes:
      - ./volumes/api/postgres:/var/lib/postgresql/data
    shm_size: '2gb'

  api_redis:
    image: redis:6.2.6-alpine
    restart: always
    networks:
      - django

  api:
    image: quay.io/sentinelc/api:${API_TAG}
    restart: always
    depends_on:
      - api_db
      - api_redis
    env_file:
      - ./configs/api.env
    networks:
      - proxy
      - django
    volumes:
      - ./volumes/api/media:/storage

  celery:
    image: quay.io/sentinelc/api:${API_TAG}
    restart: always
    depends_on:
      - api_db
      - api_redis
    env_file:
      - ./configs/api.env
    command: celery -A chinook.api worker -l INFO
    networks:
      - django
    volumes:
      - ./volumes/api/media:/storage

  beat:
    image: quay.io/sentinelc/api:${API_TAG}
    restart: always
    depends_on:
      - api_db
      - api_redis
    env_file:
      - ./configs/api.env
    command: celery -A chinook.api beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    networks:
      - django
    volumes:
      - ./volumes/api/media:/storage

  keycloak_db:
    image: postgres:14.1
    restart: always
    env_file:
      - ./configs/keycloak_db.env
    networks:
      - keycloak
    volumes:
      - ./volumes/keycloak/postgres:/var/lib/postgresql/data

  keycloak:
    image: quay.io/sentinelc/keycloak:${KEYCLOAK_TAG}
    restart: always
    depends_on:
      - keycloak_db
    env_file:
      - ./configs/keycloak.env
    networks:
      - proxy
      - keycloak
    volumes:
      - ./volumes/keycloak/import:/opt/keycloak/data/import

  front:
    image: quay.io/sentinelc/front:${FRONT_TAG}
    restart: always
    env_file:
      - ./configs/front.env
    networks:
      - proxy

  vpnrouter:
    image: quay.io/sentinelc/vpnrouter:${VPNROUTER_TAG}
    restart: always
    env_file:
      - ./configs/vpnrouter.env
    networks:
      - django
      - proxy
    cap_add:
     - NET_ADMIN
    volumes:
      - ./volumes/vpnrouter:/etc/wireguard
    ports:
      - "20208:20208/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

  portal:
    image: quay.io/sentinelc/portal:${PORTAL_TAG}
    restart: always
    env_file:
      - ./configs/portal.env
    networks:
      - proxy

  logger:
    image: quay.io/sentinelc/logger:${LOGGER_TAG}
    restart: always
    env_file:
      - ./configs/logger.env
    networks:
      - proxy
      - logger

  logger_redis:
    image: redis:6.2.6-alpine
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - logger
    volumes:
      - ./volumes/logger/redis:/data

  docs:
    image: quay.io/sentinelc/docs:${DOCS_TAG}
    restart: always
    env_file:
      - ./configs/docs.env
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/24"
  django:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.1.0/24"
  keycloak:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.2.0/24"
  logger:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.3.0/24"
