#!/usr/bin/env python3

import sys


def usage():
    print("usage: update-env [ENV FILE] [VAR] [VALUE]", file=sys.stderr)
    sys.exit(1)


def get_env_data_as_dict(path: str) -> dict:
    with open(path, 'r') as f:
       return dict(tuple(line.replace('\n', '').split('=')) for line
                in f.readlines() if not line.startswith('#'))


def main(argv):
    if len(argv) != 3:
        usage()
    
    filename = argv[0]
    var = argv[1]
    value = argv[2]
    
    env = get_env_data_as_dict(filename)
    
    current_value = env.get(var, False)
    
    if current_value != value:
        if current_value is not False:
            print(f"-{var}={current_value}")
        print(f"+{var}={value}")

        env[var] = value
    
        with open(filename, "w", encoding="utf-8") as f:
            for k,v in env.items():
                print(f"{k}={v}", file=f)


if __name__ == "__main__":
    main(sys.argv[1:])

